---
- name: Open change request
  servicenow.itsm.change_request:
    description: "{{ snow_change_request_description }}"
    impact: "{{ snow_change_request_impact }}"
    priority: "{{ snow_change_request_priority }}"
    risk: "{{ snow_change_request_risk }}"
    short_description: "{{ snow_change_request_short_description }}"
    state: new
    type: "{{ snow_change_request_type }}"
    other:
      expected_start: "{{ lookup('ansible.builtin.pipe', 'date +%Y-%m-%d') }}"
  register: snow_change

- name: Print record number
  ansible.builtin.debug:
    var: snow_change.record.number

- name: "Set stats for downstream consumption"
  ansible.builtin.set_stats:
    data:
      snow_change_request_num: "{{ snow_change.record.number }}"
    aggregate: true
