---
- name: Ensure windows machines are absent
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Ensure windows systems are absent
      cloud.terraform.terraform:
        project_path: ./aws/
        state: absent

