---
- name: Create a new incident
  servicenow.itsm.incident:
    state: new
    caller: "{{ snow_incident_caller }}"
    short_description: "{{ snow_incident_short_description }}"
    description: "{{ snow_incident_description }}"
    impact: "{{ snow_incident_impact }}"
    urgency: "{{ snow_incident_urgency }}"
    other:
      category: Software
  register: __incident

- name: Print incident number
  ansible.builtin.debug:
    var: __incident.record.number

- name: Set incident number for downstream consumption
  ansible.builtin.set_stats:
    data:
      snow_incident_number: "{{ __incident.record.number }}"
    aggregate: true
