---
- name: Ensure Linux infrastructure is present
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Ensure Linux infrastructure is present
      cloud.terraform.terraform:
        project_path: "./aws/"
        state: present
        force_init: true
        backend_config_files:
          - "{{ lookup('ansible.builtin.env', 'TF_BACKEND_CONFIG_FILE') }}"
        # backend_config:
        #   region: us-east-2
        #   bucket: deparris-tfstate
        #   key: ansible-automates/linux.tfstate