---
- name: Ensure Linux infrastructure is present
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Ensure Linux infrastructure is present
      cloud.terraform.terraform:
        project_path: "./aws/"
        state: present
        force_init: true
